version: '3.3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "webserver"
    image: "hungpm/learningwithtext:1.0.0"
    ports:
      - 8001:80
    tty: True
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "/etc/timezone:/etc/timezone:ro"
